isaiahwilliams/partner-center-dotnet

- azure-pipelines.yml
Through this pull request the projects input is being updated
> Updating the projects input

- README.md
Through this pull request the build status badge is being added
> Adding the build status badge

- azure-pipelines.yml
Through this pull request the nupkg file is being included in the artifact that is generated
> Including the nupkg file in the artifact

- README.md
Through this pull request the deployment badge is being added
> Adding the deployment badge

- src/PartnerCenter/Extensions/ApplicationPartnerCredentials.cs
- src/PartnerCenter/PartnerCenter.csproj
Through this pull requests the required changes to transition from ADAL to MSAL are being made
> Switching from ADAL to MSAL

- src/PartnerCenter/Agreements/AgreementDetailsCollectionOperations.cs
- src/PartnerCenter/Agreements/CustomerAgreementCollectionOperations.cs
- src/PartnerCenter/Agreements/IAgreementDetailsCollection.cs
- src/PartnerCenter/Agreements/ICustomerAgreementCollection.cs
Through this pull request the agreement operations are being updated
> Agreement feature update

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
- src/PartnerCenter/Agreements/AgreementDocumentOperations.cs
- src/PartnerCenter/Agreements/AgreementTemplateCollectionOperations.cs
- src/PartnerCenter/Agreements/AgreementTemplateOperations.cs
- src/PartnerCenter/Agreements/IAgreementDocument.cs
- src/PartnerCenter/Agreements/IAgreementTemplate.cs
- src/PartnerCenter/Agreements/IAgreementTemplateCollection.cs
- src/PartnerCenter/Configuration/PartnerService.json
- src/PartnerCenter/IPartner.cs
- src/PartnerCenter/Models/Agreements/AgreementDocument.cs
- src/PartnerCenter/Models/Agreements/AgreementDocumentContext.cs
- src/PartnerCenter/Models/Agreements/AgreementDocumentTransformOptions.cs
- src/PartnerCenter/Models/Agreements/AgreementTemplateContext.cs
- src/PartnerCenter/Network/PartnerServiceClient.cs
- src/PartnerCenter/PartnerOperations.cs
Through this pull request the agreement operations are being updated
> Updating the agreement operations

- src/PartnerCenter/Extensions/ApplicationPartnerCredentials.cs
- src/PartnerCenter/PartnerCenter.csproj
Through this pull request the issue with the authority in the application credentials is being corrected
#13
> Addressing issue with the authority used with application credentials

- src/PartnerCenter/Extensions/ApplicationPartnerCredentials.cs
- src/PartnerCenter/PartnerCenter.csproj
Through this pull request the changes from the master branch are being merged into the dev branch.
> Authentication update

- README.md
- azure-pipelines.yml
Through this pull request the build configuration is being updated
> Updating the build configuration

- src/PartnerCenter.TestFramework/Network/HttpMockHandler.cs
- src/PartnerCenter/Configuration/PartnerService.json
- src/PartnerCenter/IPartner.cs
- src/PartnerCenter/Models/Invoices/OneTimeInvoiceLineItem.cs
- src/PartnerCenter/Models/ProductUpgrades/ProductUpgradesEligibility.cs
- src/PartnerCenter/Models/ProductUpgrades/ProductUpgradesErrorDetails.cs
- src/PartnerCenter/Models/ProductUpgrades/ProductUpgradesLineItem.cs
- src/PartnerCenter/Models/ProductUpgrades/ProductUpgradesRequest.cs
- src/PartnerCenter/Models/ProductUpgrades/ProductUpgradesStatus.cs
- src/PartnerCenter/Models/ProductUpgrades/UpgradedProductDetails.cs
- src/PartnerCenter/Models/Subscriptions/AzureEntitlement.cs
- src/PartnerCenter/PartnerCenter.csproj
- src/PartnerCenter/PartnerOperations.cs
- src/PartnerCenter/ProductUpgrades/IProductUpgrades.cs
- src/PartnerCenter/ProductUpgrades/IProductUpgradesCollection.cs
- src/PartnerCenter/ProductUpgrades/ProductUpgradesCollectionOperations.cs
- src/PartnerCenter/ProductUpgrades/ProductUpgradesOperations.cs
- src/PartnerCenter/Subscriptions/ISubscription.cs
- src/PartnerCenter/Subscriptions/SubscriptionOperations.cs
- src/PartnerCenter/Usage/SubscriptionUsageRecordCollectionOperations.cs
Through this pull request support for the Azure Plan is being added.
> Adding support for the Azure Plan

- src/PartnerCenter/Models/Invoices/DailyRatedUsageLineItem.cs
- src/PartnerCenter/Models/Usage/CustomerMonthlyUsageRecord.cs
- src/PartnerCenter/Models/Usage/ResourceUsageRecord.cs
Through this pull request updates are being made to the invoice and usage models
> Updates to the invoice and usage models

- README.md
- src/PartnerCenter/Models/Invoices/OneTimeInvoiceLineItem.cs
Through this pull request the billing frequency property is being added.
> Adding the billing frequency property

- CHANGELOG.md
- src/PartnerCenter.TestFramework/PartnerCenter.TestFramework.csproj
- src/PartnerCenter/CustomerUsers/CustomerUsersCollectionOperations.cs
- src/PartnerCenter/PartnerCenter.csproj
Through this pull request changes are being made for the upcoming release
> Release update

- azure-pipelines.yml
- build.proj
- src/PartnerCenter.TestFramework/Network/HttpUtilities.cs
- src/PartnerCenter.TestFramework/PartnerCenter.TestFramework.csproj
- src/PartnerCenter/Compliance/AgreementSignatureStatusOperations.cs
- src/PartnerCenter/Compliance/ComplianceCollectionOperations.cs
- src/PartnerCenter/Compliance/IAgreementSignatureStatus.cs
- src/PartnerCenter/Compliance/IComplianceCollection.cs
- src/PartnerCenter/Configuration/PartnerService.json
- src/PartnerCenter/IPartner.cs
- src/PartnerCenter/Models/Compliance/AgreementSignatureStatus.cs
- src/PartnerCenter/Network/PartnerServiceClient.cs
- src/PartnerCenter/PartnerCenter.csproj
- src/PartnerCenter/PartnerOperations.cs
- test/PartnerCenter.UnitTests/PartnerCenter.UnitTests.csproj
- test/PartnerCenter.UnitTests/TestBase.cs
Through this pull request the following changes are being made
- Adding the ability to trace the HTTP operations
- Adding the compliance operations used to check if an indirect reseller has accept the Microsoft Partner Agreement
- Updating build and test configurations to use .NET Core 3.0
> Tracing feature update

- CHANGELOG.md
- src/PartnerCenter/Models/Invoices/DailyRatedUsageLineItem.cs
- src/PartnerCenter/Models/JsonConverters/NestedResourceConverter.cs
Through this pull request the following changes are being made 
- Addressing an issue that was preventing nested JSON strings from being deserialized correctly
- Updating the change log to reflect the recent changes 
> Invoice feature update

- src/PartnerCenter/Network/PartnerServiceClient.cs
Through this pull request the ability to trace a response is being added
> Adding the ability to trace a response

- CHANGELOG.md
- src/PartnerCenter/Subscriptions/ISubscriptionCollection.cs
- src/PartnerCenter/Subscriptions/SubscriptionCollectionOperations.cs
Through this pull request the request to get subscriptions by partner is being updated
> Updating the request to get subscriptions by partner

- CHANGELOG.md
- src/PartnerCenter/PartnerCenter.csproj
- src/PartnerCenter/ProductUpgrades/ProductUpgradesCollectionOperations.cs
Through this pull request the following changes are being made
- Added the Source Link configuration
- Addressed an issue with the way a product upgrade was being created
> Addressed an issue with the way a product upgrade was being created

- CHANGELOG.md
- src/PartnerCenter.TestFramework/PartnerCenter.TestFramework.csproj
- test/PartnerCenter.UnitTests/PartnerCenter.UnitTests.csproj
Through this pull request the version information is being updated
> Updating the version information

- src/PartnerCenter.TestFramework/PartnerCenter.TestFramework.csproj
- src/PartnerCenter/Network/PartnerServiceClient.cs
- src/PartnerCenter/PartnerCenter.csproj
- src/PartnerCenter/PartnerService.cs
- test/PartnerCenter.UnitTests/PartnerCenter.UnitTests.csproj
Through this pull request the ability to create an instance of the partner operations class with a request context is being added. 
> Request context feature update

- src/PartnerCenter/Agreements/AgreementDocumentOperations.cs
Updating the agreement document feature 
[262](https://github.com/microsoft/Partner-Center-PowerShell/issues/262)
> Addressing issue with the get agreement document

- src/PartnerCenter/Network/PartnerServiceClient.cs
Through this pull request the way exceptions are parsed is being updated
[258](https://github.com/microsoft/Partner-Center-PowerShell/issues/258)
> Updating how exceptions are parsed

- CHANGELOG.md
- azure-pipelines.yml
- src/PartnerCenter/Agreements/AgreementDocumentOperations.cs
- src/PartnerCenter/Network/PartnerServiceClient.cs
- src/PartnerCenter/PartnerCenter.csproj
Through this pull request the agreement and network features are being updated.
> Addressing two minor regressions and updating the version
